task :environment do
  require 'rubygems'
  require 'activerecord'
  require 'db_connect.rb'
  require 'models.rb'
end

namespace :db do
  desc "Migrate the database"
  task(:migrate => :environment) do
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Migration.verbose = true
    ActiveRecord::Migrator.migrate("db/migrate")
  end 
end

