source 'https://rubygems.org'

gem "sinatra"
gem "sqlite3"
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"

group :development, :test do
  gem "sinatra-contrib"
  gem "rspec"
  gem "factory_girl"
end
