require 'bundler/setup'
Bundler.require(:default)
require 'resque/tasks'
require 'sinatra/activerecord/rake'
require_relative 'app.rb'

task 'resque:setup' do
  ENV['QUEUE'] = '*'
end

desc 'Alias for resque:work (To run workers on Heroku)'
task 'jobs:work' => 'resque:work'
